
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          curl -o 1.html https://www.baidu.com/#ie=UTF-8&wd=%E5%BA%B7%E7%86%99%E6%80%92%E6%96%A5%E7%BE%A4%E8%87%A3%20%E5%8F%B0%E8%AF%8D
          git config --local user.email "1662916172@qq.com"
          git config --local user.name "CCR-Studio"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git add *
          git commit -m "test"
          git push
