
name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          curl -o scb.jar https://edge.forgecdn.net/files/2770/968/simplecoloredblocks-1.2.1.jar
          git add *
          git commit -m "test"
          git push
