
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          curl -o 1.html https://www.google.com/search?q=simplecoloredblocks&oq=simplecoloredblocks&aqs=chrome..69i64j69i57j69i58.6542j0j1&sourceid=chrome&ie=UTF-8
          git config --local user.email "1662916172@qq.com"
          git config --local user.name "CCR-Studio"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git add *
          git commit -m "test"
          git push
