
name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          curl -o 1.css https://fonts.googleapis.com/css?family=Lato&display=swap
          curl -o buefy.min.css https://unpkg.com/buefy@0.9.13/dist/buefy.min.css
          curl -o jquery.min.js https://unpkg.com/jquery@3.6.0/dist/jquery.min.js
          curl -o vue.min.js https://unpkg.com/vue@2.6.14/dist/vue.min.js
          curl -o buefy.min.js https://unpkg.com/buefy@0.9.13/dist/buefy.min.js
          curl -o popper.min.js https://unpkg.com/@popperjs/core@2.9.2/dist/umd/popper.min.js
          curl -o Sortable.min.js https://unpkg.com/sortablejs@1.10.2/Sortable.min.js
          curl -o 1.js https://www.googletagmanager.com/gtag/js?id=G-CPC46V71CB
          git config --local user.email "1662916172@qq.com"
          git config --local user.name "CCR-Studio"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git add *
          git commit -m "test"
          git push
